---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
    driver:
      run_command: /usr/sbin/init
  - name: fedora-22
    driver:
      run_command: /usr/sbin/init
  - name: ubuntu-16.04
    driver:
      run_command: /sbin/init

suites:
  - name: install
    run_list:
      - recipe[plex::install_pms]
    attributes:
      plex:
        service_provider: Chef::Provider::Service::Systemd
  - name: install_and_start
    run_list:
      - recipe[plex::install_and_start_pms]
    attributes:
      plex:
        service_provider: Chef::Provider::Service::Systemd
  - name: uninstall
    run_list:
      - recipe[plex::install_and_start_pms]
      - recipe[plex::uninstall_pms]
    attributes:
      plex:
        service_provider: Chef::Provider::Service::Systemd
  - name: reinstall
    run_list:
      - recipe[plex::install_pms]
      - recipe[plex::uninstall_pms]
      - recipe[plex::install_and_start_pms]

verifier:
  name: inspec
