---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
  - name: fedora-24
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[plex::default]

verifier:
  name: inspec
