---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
  - name: fedora-24
  - name: ubuntu-16.04

suites:
  - name: install
    run_list:
      - recipe[plex::install_pms]
  - name: install_and_start
    run_list:
      - recipe[plex::install_and_start_pms]
  - name: uninstall
    run_list:
      - recipe[plex::install_and_start_pms]
      - recipe[plex::uninstall_pms]
  - name: reinstall
    run_list:
      - recipe[plex::install_pms]
      - recipe[plex::uninstall_pms]
      - recipe[plex::install_and_start_pms]

verifier:
  name: inspec
